### ISSUE TITLE
每次Ctrl+alt+2会弹出都会新弹出一个窗口

### ISSUE THREAD

**Issue by zuilintan** [dengzii/WiFiADB#10]
能否置为全局唯一呢, 且始终比IDEA的窗口优先级高(偶尔被IDEA盖住找不到)

**Comment by dengzii** [comment]
@zuilintan 感谢提议

 原本窗口是模态框（必须关闭才能继续操作父级窗口）， 后来忘了是什么原因改成非模态框，下次更新将改为模态框。
