### ISSUE TITLE
偶尔出现按下快捷键会弹出多个插件窗口

### ISSUE THREAD

**Issue by ChenilleJoes** [dengzii/WiFiADB#11]
刚才按下快捷键Ctrl+Alt+2的时候弹出两个窗口，还有一次弹出三个窗口，但是只有最上层可以操作，关闭了最上层的，下层窗口也一并关闭(并不影响使用)，但是我没法复现此情况(按记忆中出现此情况的前几步操作没再出现(感觉越说越乱😂)

**Comment by dengzii** [comment]
感谢提出建议, 现在已经改好了, 主窗口现在是模态框, 不会出现多次打开的情况了. 并且是在最上层,不关闭无法操作IDE
