### ISSUE TITLE
failed to connect to '192.168.1.10:5555' connection refused

### ISSUE THREAD

**Issue by Drjacky** [dengzii/WiFiADB#12]
<img width="838" alt="Screen Shot 2020-07-20 at 11 30 18" src="https://user-images.githubusercontent.com/2296754/87922519-65bf1b00-ca7c-11ea-8c80-655d8473ae9a.png">

**Comment by dengzii** [comment]
This error may be due to the following reasons

- The phone has turned off the port 5555 (when you reboot phone).

- The ip has changed when you reconnect to WiFi.

**Comment by Drjacky** [comment]
I've checked the IP, it's the same.
About port, not sure.
Anyway, after a while, now it connects! Maybe because I used [another plugin](https://plugins.jetbrains.com/plugin/9717-adb-wifi-connect/) to connect over wifi, and it somehow helped.

**Comment by dengzii** [comment]
That's good, this plugin is relies to adb command line, there's a lot of uncertainty, the error log can found in menu `Main > Log`.
If it's doesn't work, in most cases, you just reconnect device by USB and click connect , it will work well again.
Finally, thank you for your  issue.
