### ISSUE TITLE
Android Studio dose not work

### ISSUE THREAD

**Issue by limelect** [dengzii/WiFiADB#16]
Android Studio 4.1.1 does not work
S6 phone attached with cable.

**Comment by dengzii** [comment]
Are there any error messages. or can you provide the log.

**Comment by limelect** [comment]
Sorry, it seems it cannot be connected to Android Studio. I have a red msg cannot install.

**Comment by dengzii** [comment]
Hi, I released a new version, some bugs fixed in this version.
