### ISSUE TITLE
建议添加列表项直接修改IP与port和每个项单独删除的功能

### ISSUE THREAD

**Issue by zuilintan** [dengzii/WiFiADB#2]
很多时候, 咱们的设备的IP是变得, 时间长了列表内到处都是过期的项, 
但还有些未过期的, 全部移除肯定是比较麻烦的, 
单独删除或者直接修改IP是个不错的解决方案

**Comment by MrDenua** [comment]
感谢提议
我将在下次更新时考虑添加此功能

**Comment by gedoor** [comment]
催更

**Comment by dengzii** [comment]
在 V2.5 版本中，已支持右键删除设备
