### ISSUE TITLE
扫描的速度有待提升

### ISSUE THREAD

**Issue by zuilintan** [dengzii/WiFiADB#20]
可以尝试下多线程?

**Comment by dengzii** [comment]
有多线程啊, 默认就是 Runtime.getRuntime().availableProcessors(), 可以把它设为两倍, 我这测试一遍六七秒就OK了

**Comment by dengzii** [comment]
没有多线程没法玩的啊, 贼慢, 一般局域网 254个主机要扫描, 每个主机要扫描 4 个端口, ping 等等超时 1秒, 端口扫描超时 1秒, 不并行扫描算下来得几分钟了

**Comment by zuilintan** [comment]
抱歉, 没看仔细, 的确有多线程
