### ISSUE TITLE
已知第三段地址时, 扫描优化建议

### ISSUE THREAD

**Issue by zuilintan** [dengzii/WiFiADB#21]
![image](https://user-images.githubusercontent.com/34953840/102154877-4dc9b700-3eb5-11eb-92cc-781956dfd234.png)
很多时候, 咱们是知道第三段地址的, 
这样只扫描255次即可, 
能否手动指定扫描范围呢?

**Comment by dengzii** [comment]
是, 一般局域网是可以分配 255 个 IP, 出去路由和广播地址, 还剩 254, 我这就是扫描 254 个地址, 首先判断是否可达性, 再判断端口是否开放.

**Comment by zuilintan** [comment]
不是的哈, 我是指限定扫描范围是如
192.168.137.x, 这样的形式

**Comment by dengzii** [comment]
这个可以, 我后面更新时加上

**Comment by dengzii** [comment]
[3.0](https://github.com/dengzii/WiFiADB/releases/tag/3.0) 已添加
