### ISSUE TITLE
Connect Manual 连接指定IP后无效果

### ISSUE THREAD

**Issue by zuilintan** [dengzii/WiFiADB#22]
![image](https://user-images.githubusercontent.com/34953840/102158160-c59ae000-3ebb-11eb-876a-3b36320f786b.png)
连接后回到主界面, 但没有任何Item刷新出来

**Comment by dengzii** [comment]
这说明连接失败了, 一般会有提示

**Comment by zuilintan** [comment]
奇怪, 2.8没问题的哈

**Comment by dengzii** [comment]
🤔这个工具我觉得不太稳定, 因为是用 CMD 命令实现的, 很多问题不好处理

**Comment by dengzii** [comment]
[3.0](https://github.com/dengzii/WiFiADB/releases/tag/3.0) 已修复
