### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by limelect** [dengzii/WiFiADB#23]
changing old jar with new
	Plugin Error: Plugin "Android WiFi ADB" is incompatible (supported only in IntelliJ IDEA).
The old one loads but had bugs

**Comment by dengzii** [comment]
What's your AnroidStudio version, I install successful in version 4.1.1, it's works.
This plugin compatible lowest AndroidStudio version ` build 183.4284.148+`, it's verification by `JetBrains Plugin Repository`

**Comment by limelect** [comment]
1. 4.1.1
2. You are not on the market
3. I put your latest in the plugin directory.
4. Since Delphi is my main i moved on to https://github.com/ms301/Delphi-Adb-WiFi
5. I do not need a USB at first!!!!

**Comment by dengzii** [comment]
Could something else have gone wrong. the latest version not in Market because it's under Markplace review, It passed the  compatibility verification.

**Comment by limelect** [comment]
I have downloaded you latest

**Comment by dengzii** [comment]
Fine, thanks for your advice.
