### ISSUE TITLE
Scan Device的Scan IP范围有误

### ISSUE THREAD

**Issue by zuilintan** [dengzii/WiFiADB#24]
![image](https://user-images.githubusercontent.com/34953840/102435664-fad93680-4051-11eb-9f0f-e9323581620d.png)
以太网是以172开头, 这里显示的是169

**Comment by zuilintan** [comment]
或许可以将这部分完全交由用户去定义?
x.x.x.x
以Win10热点为例, 
其IP又是由192开头

**Comment by dengzii** [comment]
你那是有多个网卡吧, 默认获取  localhost 所在的网卡

**Comment by dengzii** [comment]
这个范围没法定义的, ip 地址很难指定具体的一定的范围, 这个是根据子网掩码来的

**Comment by zuilintan** [comment]
> 你那是有多个网卡吧, 默认获取 localhost 所在的网卡

对的

**Comment by zuilintan** [comment]
> 你那是有多个网卡吧, 默认获取 localhost 所在的网卡

的确, 和我其中一个网卡的IP段一样

**Comment by zuilintan** [comment]
有办法主动指定某一个网卡吗?

**Comment by dengzii** [comment]
可以指定

**Comment by zuilintan** [comment]
新年好啊~, 
后面如果加入了指定网卡的功能, 
可以考虑下记忆网卡及IP范围, 避免后续打开重复指定
(悄悄催更.gif)

**Comment by dengzii** [comment]
🤣 好啊

**Comment by dengzii** [comment]
👏 选择网卡有了, 3.6 版本
