### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by AtulRaj007** [dengzii/WiFiADB#25]
Hi 
I am not able to connect device wirelessly on Android studio.
It failed to connect but previously it was working.
I am able to connect via usb or manual approach using Ip Address.

**Comment by dengzii** [comment]
Hi, 
This is maybe because device ip or port has changed, check the device ip and port in table whether same with manual input.
If these two are the same, please reply me the log when connect failed.

**Comment by P1NG2WIN** [comment]
Same issue after update plugin in android studio. New version wont work at all

**Comment by dengzii** [comment]
This is terrible, I will find out the bug as soon as possible.
