### ISSUE TITLE
3.2 bug?

### ISSUE THREAD

**Issue by badboy-tian** [dengzii/WiFiADB#28]
![image](https://user-images.githubusercontent.com/2835129/104589333-a94db700-56a4-11eb-86bd-d962d355f88e.png)

Android studio 4.1.1

**Comment by badboy-tian** [comment]
分别点 Toos->wifiAdb

**Comment by dengzii** [comment]
谢谢, 使用了 jdk11 编译导致了这个问题, `3.3` 已修复
