### ISSUE TITLE
close but no cigar

### ISSUE THREAD

**Issue by kencoppersmith25** [dengzii/WiFiADB#29]
hello - my device is showing with a status of "CONNECTED" in the WiFiADB Tools dialog yet off the main screen, the small drop down showing my phone (samsung SM-G950U and next to the app dropdown) is disabled.

**Comment by dengzii** [comment]
Hi, I can't judge the cause of the problem, it may not be a bug of plugin.
You can try reopen the `Developer Options` and `USB Debug`, or find out the cause from `Android Studio > small dropdown option (device list) > TroubleShoot Device Connections`.

**Comment by kencoppersmith25** [comment]
Thank you, dengzi!  It was a dfu error.  I’m sure you know that one.  Dumb F’n User.
Have a good day.
Ken

Sent from Mail for Windows 10

**Comment by dengzii** [comment]
I'm glad I can help you, have a good day to you too.
