### ISSUE TITLE
[Feature request] Connect Manual使用频率相当之高, 可否考虑将其将其移置工具栏?

### ISSUE THREAD

**Issue by zuilintan** [dengzii/WiFiADB#31]
![image](https://user-images.githubusercontent.com/34953840/110234591-41aa3e80-7f66-11eb-99ac-a5b302eaa3fc.png)
这个功能, 在全部的plugins商店中独有, 应该醒目一些

**Comment by zuilintan** [comment]
另外, 每次启动后, 窗口大小都有问题
![image](https://user-images.githubusercontent.com/34953840/110234655-9ea5f480-7f66-11eb-9add-f793d43f7f04.png)

**Comment by dengzii** [comment]
[3.4](https://github.com/dengzii/WiFiADB/releases/tag/3.4) 已更新
