### ISSUE TITLE
MacOS bigsur，AS4.1.2，插件版本3.3，每次启动都显示adb command is unavailable但是sdk路径绝对没有错

### ISSUE THREAD

**Issue by liyuhaolol** [dengzii/WiFiADB#32]
每次都要手动设置，太麻烦了点吧，这是BUG吧？？

**Comment by dengzii** [comment]
只是无法记忆设置吗, 重新设置就有用了吗, `SDK/platform-tools/adb`

**Comment by liyuhaolol** [comment]
> 只是无法记忆设置吗, 重新设置就有用了吗, `SDK/platform-tools/adb`

是无法自动加载记忆的adb设置，每次重启AS回来，点开插件，就会报那个错，选项框里adb路径是保存住并显示的，但是会报adb command is unavailable，直接点确定手动加载才能好。

**Comment by dengzii** [comment]
好家伙, 最新版 3.5 已修复, 感谢提出问题👍
