### ISSUE TITLE
Menu item missing from Tools

### ISSUE THREAD

**Issue by KonTe1989** [dengzii/WiFiADB#34]
Menu item WifiADB Tool is missing from Tools menu on Android Studio 4.1.2 Windows 10

After instalation of the plugin, menu item is present. If i restart the studio and open it again the menu item is missing but its accesible via CTRL + ALT + 2 shortcut.

If i reinstall the plugin same happens. After restart menu item missing.

**Comment by dengzii** [comment]
I cannot reproduce that problem on AndroidStudio 4.1.2. same steps.
