### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by OscarCaro** [dengzii/WiFiADB#36]
On the forums that explain how to connect adb over wifi manually ( i.e. [stackoverflow](https://stackoverflow.com/questions/4893953/run-install-debug-android-applications-over-wi-fi) ) they always warn that it's dangerous to leave the configuration up after using it, because it allows anyone on your network to access your phone the same way.
My concern is: does this plugin take that into account? Is there any security measurement to avoid that problem?

Thank you in advance. I'll close the issue as soon as you explain it.

**Comment by dengzii** [comment]
Thanks for your advice. 

In most cases, you don't need to think about these problem. most of the time your LAN is secure, some devices will close the port after reboot, disconnect adb or disconnect WiFi. we can only hope there are no bad guys,  there is no other way to avoid that problem.

**Comment by OscarCaro** [comment]
Yes, after a while using this tool, I realised my phone is actually closing the TCP port automatically after an inactivity period, so there's no risk of leaving the port open.
Thanks.
