### ISSUE TITLE
[Feature request] The plugin should attempt to auto-locate ADB

### ISSUE THREAD

**Issue by NoahAndrews** [dengzii/WiFiADB#37]
**Is your feature request related to a problem? Please describe.**
Most people don't know where they have ADB installed, and probably don't have it in their PATH variable. So when the first thing they see from this plugin is a blank field for them to enter the ADB path, they're not going to know what to do.

I'd like to be able to recommend this plugin to users of the [REV Control Hub](https://www.revrobotics.com/rev-31-1595/) without having to walk them through entering the ADB path.

**Describe the solution you'd like**
Before asking the user where ADB lives, the plugin should look in the most common locations for it. On macOS, that's `/Users/USERNAME/Library/Android/sdk` (according to [this](https://stackoverflow.com/a/34532235/4651874)), on Windows, that's `C:\Users\USERNAME\AppData\Local\Android\Sdk\platform-tools\adb.exe`, and on Linux that's `/home/USERNAME/Android/Sdk` (according to [this](https://stackoverflow.com/a/43330574/4651874)).

**Describe alternatives you've considered**
Another thing that would be a good idea is to include a Browse button in the ADB path prompt.

**Comment by dengzii** [comment]
Thanks for your advise, your suggestion is very good, I will consider adding this feature in the next release.

**Comment by NoahAndrews** [comment]
Thank you!

**Comment by dengzii** [comment]
All your suggestions have been implemented in the latest version [3.6](https://github.com/dengzii/WiFiADB/releases/tag/3.6).
Thanks again for your advice.

**Comment by NoahAndrews** [comment]
Wow, that was fast. Thank you so much for developing this lovely piece of software.
