### ISSUE TITLE
[Feature request] Allow users to add a wireless ADB connection when the device is not currently available

### ISSUE THREAD

**Issue by NoahAndrews** [dengzii/WiFiADB#38]
**Is your feature request related to a problem? Please describe.**
One of the REV Control Hub users pointed out to us that when they are hosting a video call to help users learn how to use their devices, it is annoying to have to have users disconnect from the video call in order to set up the wireless ADB connection to their Control Hub (the Control Hub broadcasts its own WiFi network that users have to connect to).

**Describe the solution you'd like**
An "Add device to list even if the device is not currently available" checkbox could be added to the manual connection dialog.

**Describe alternatives you've considered**
The "Failed, cannot connect to..." error message that shows up at the bottom of the main WiFiADB window could include a button to add the device to the list anyway.

**Additional context**
There's also a bug where the previously-mentioned error message is clipped at the edge of the window, instead of wrapping to a new line:

![image](https://user-images.githubusercontent.com/10224994/115592576-00ad8580-a299-11eb-874c-ff4c183f1534.png)

**Comment by dengzii** [comment]
Thanks for your suggestion.

 Version 3.7 has updated the features you suggested 🎉, add to device list when connection fails, and the ui self-adapting now.

**Comment by NoahAndrews** [comment]
Impressive speed again! Thank you!
