### ISSUE TITLE
Conflicting descriptions

### ISSUE THREAD

**Issue by gerrywastaken** [dengzii/WiFiADB#40]
This project states two different descriptions and I'm not sure which one is the correct one:

![intellij-vs-android-studio](https://user-images.githubusercontent.com/71481/127766901-e0774a48-2287-4b2b-8b49-1c3e74b44916.png)

**Comment by dengzii** [comment]
The README is the correct one.

**Comment by gerrywastaken** [comment]
Thanks for updating the About section :+1:
