### ISSUE TITLE
无线调试扫描端口速度太慢了

### ISSUE THREAD

**Issue by 2e2ee95304418f96** [dengzii/WiFiADB#41]
虽然用了16个线程，但是adb扫描端口还是太慢了

测试了一下，每个端口超时时间200ms，16个线程，设备ip是固定的，扫描100个端口就需要20秒.

实际情况是，手机开启无线调试的端口是随机65535个端口（前1000个端口应该不会占用），那要是自动扫描就太慢了。不知道有没有什么好办法？

还有个问题，自动扫描配置的内容不能保存，每次还要再填一遍。

**Comment by dengzii** [comment]
扫描只会扫描固定的那几个端口(手机adb端口我记得是固定的范围内的), 然后整个网段扫描, 一般是254台机器 , 没有其他好办法了, 配置记录的后面看看, 下次更新的时候添加

**Comment by 2e2ee95304418f96** [comment]
> 扫描只会扫描固定的那几个端口(手机adb端口我记得是固定的范围内的), 然后整个网段扫描, 一般是254台机器 , 没有其他好办法了, 配置记录的后面看看, 下次更新的时候添加

android11自带一个无线调试，打开后是随机65535内的端口，经常都是大端口（40000之类），主动去扫描这条路不太行了，我想的是客户端打开后上报到PC端，不知道插件是否容易实现带http server的。

**Comment by dengzii** [comment]
这个办法我想过, 但是需要手机安装app, 没有 root 可行性不知道高不高
