### ISSUE TITLE
Device not connecting

### ISSUE THREAD

**Issue by avid00** [dengzii/WiFiADB#42]
**Describe the bug**
Not much to say, the device shows up in the list but when I click connect, the msg changes to 'connecting' but nothing happens after that i.e it stays disconnected and the msg changes to 'all devices are listed'. 
I refreshed, restarted AS, same thing.

**To Reproduce**
Just configured and connected a device yesterday. worked earlier. opened the plugin after sometime (after shutting down pc) same way as always.

**Screenshots**

**Context Log**
From `Menu > Main > Log`

08-10/19:16 CmdUtils.execSync:48: adb version
08-10/19:16 CmdUtils$resolve$1.accept:76: >Android Debug Bridge version 1.0.41
08-10/19:16 CmdUtils$resolve$1.accept:76: >Version 31.0.3-7562133
08-10/19:16 CmdUtils$resolve$1.accept:76: >Installed as C:\Users\AMY\AppData\Local\Android\Sdk\platform-tools\adb.exe
08-10/19:16 Config.loadDevices:50: [Device(sn='192.168.1.4:5555', ip='192.168.1.4', model='moto_g_7__power', modelName='ocean', port='5555', status=DISCONNECTED, broadcastAddress='',mark=)]
08-10/19:16 CmdUtils.execSync:48: adb devices -l
08-10/19:16 CmdUtils$resolve$1.accept:76: >List of devices attached
08-10/19:16 CmdUtils$resolve$1.accept:76: >
08-10/19:16 Config.saveDevice:57: [Device(sn='192.168.1.4:5555', ip='192.168.1.4', model='moto_g_7__power', modelName='ocean', port='5555', status=DISCONNECTED, broadcastAddress='',mark=)]
08-10/19:16 DeviceManager.connectDevice:55: Device(sn='192.168.1.4:5555', ip='192.168.1.4', model='moto_g_7__power', modelName='ocean', port='5555', status=DISCONNECTED, broadcastAddress='',mark=)
08-10/19:16 CmdUtils.execSync:48: adb connect 192.168.1.4:5555
08-10/19:16 CmdUtils$resolve$1.accept:76: >cannot connect to 192.168.1.4:5555: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060)
08-10/19:16 Config.loadDevices:50: [Device(sn='192.168.1.4:5555', ip='192.168.1.4', model='moto_g_7__power', modelName='ocean', port='5555', status=DISCONNECTED, broadcastAddress='',mark=)]
08-10/19:16 CmdUtils.execSync:48: adb devices -l
08-10/19:16 CmdUtils$resolve$1.accept:76: >List of devices attached
08-10/19:16 CmdUtils$resolve$1.accept:76: >
08-10/19:16 Config.saveDevice:57: [Device(sn='192.168.1.4:5555', ip='192.168.1.4', model='moto_g_7__power', modelName='ocean', port='5555', status=DISCONNECTED, broadcastAddress='',mark=)]
08-10/19:17 DeviceManager.connectDevice:55: Device(sn='192.168.1.4:5555', ip='192.168.1.4', model='moto_g_7__power', modelName='ocean', port='5555', status=DISCONNECTED, broadcastAddress='',mark=)
08-10/19:17 CmdUtils.execSync:48: adb connect 192.168.1.4:5555
08-10/19:17 CmdUtils$resolve$1.accept:76: >cannot connect to 192.168.1.4:5555: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060)
08-10/19:17 Config.loadDevices:50: [Device(sn='192.168.1.4:5555', ip='192.168.1.4', model='moto_g_7__power', modelName='ocean', port='5555', status=DISCONNECTED, broadcastAddress='',mark=)]
08-10/19:17 CmdUtils.execSync:48: adb devices -l
08-10/19:17 CmdUtils$resolve$1.accept:76: >List of devices attached
08-10/19:17 CmdUtils$resolve$1.accept:76: >
08-10/19:17 Config.saveDevice:57: [Device(sn='192.168.1.4:5555', ip='192.168.1.4', model='moto_g_7__power', modelName='ocean', port='5555', status=DISCONNECTED, broadcastAddress='',mark=)]
08-10/19:17 DeviceManager.connectDevice:55: Device(sn='192.168.1.4:5555', ip='192.168.1.4', model='moto_g_7__power', modelName='ocean', port='5555', status=DISCONNECTED, broadcastAddress='',mark=)
08-10/19:17 CmdUtils.execSync:48: adb connect 192.168.1.4:5555
08-10/19:17 CmdUtils$resolve$1.accept:76: >cannot connect to 192.168.1.4:5555: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060)
08-10/19:17 Config.loadDevices:50: [Device(sn='192.168.1.4:5555', ip='192.168.1.4', model='moto_g_7__power', modelName='ocean', port='5555', status=DISCONNECTED, broadcastAddress='',mark=)]
08-10/19:17 CmdUtils.execSync:48: adb devices -l
08-10/19:17 CmdUtils$resolve$1.accept:76: >List of devices attached
08-10/19:17 CmdUtils$resolve$1.accept:76: >
08-10/19:17 Config.saveDevice:57: [Device(sn='192.168.1.4:5555', ip='192.168.1.4', model='moto_g_7__power', modelName='ocean', port='5555', status=DISCONNECTED, broadcastAddress='',mark=)]

**Comment by dengzii** [comment]
Hello, 
The log indicated your phone maybe closed the adb port, the message show 'all devices are listed' because execute `refresh` every times after operate device, the connect error message is replaced.

> 08-10/19:17 CmdUtils$resolve$1.accept:76: >cannot connect to 192.168.1.4:5555: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060)

Some device will close the adb port when disconnect adb service after a certain amount of time.
