### ISSUE TITLE
Custom shortcut

### ISSUE THREAD

**Issue by A2va** [dengzii/WiFiADB#44]
**Is your feature request related to a problem? Please describe.**
On my keyboard, for type a "@" you must Ctrl+Alt+2 which is exatly the shortcut of WifiADB and the at sign is quite useful in Java and javadoc  . 

**Describe the solution you'd like**
I want a way to set a shortcut for opening WifiABD GUI.

**Comment by dengzii** [comment]
You can change the shortcut key in AndroidStudio from `File > Settings > Keymap`, enter `WiFiADB` into the input box, you can find the plugin shortcut key in the list and right mouse button to change it.
