### ISSUE TITLE
Why would you impose us paid version

### ISSUE THREAD

**Issue by zakblacki** [dengzii/WiFiADB#46]
Very disappointing I was using this daily, now have to look for another

**Comment by Simranjit-contact** [comment]
I suddenly started getting the paid licence prompt while creating my college project.
Extremely annoying. There was no indication that it was paid when I downloaded it and it's a weird timing to end the "trial" if there even was one. I can't even figure out how to even buy it, there's no clear option to "obtain the licence" this is so stupid.
Now I gotta look for another better free option.

**Comment by dengzii** [comment]
The paid version is alwas optional, all of  the GitHub release version is free version.

Trials are also optional, maybe you are using an older version of the AndroidStudio, the older version is not support JetBrains MarketPlace License. 

I've been maintaining this plugin for nearly two years, and I'm hoping that some support will keep me motivated to keep updating it.

Thanks you all.

**Comment by zakblacki** [comment]
I'm using latest android version and this only happened today after you updated the plugin asking us either to use paid or evaluate .
