### ISSUE TITLE
MARK not save

### ISSUE THREAD

**Issue by arm19jong** [dengzii/WiFiADB#49]
Android Studio chipmunk 2021.2.1 Path1
[WiFiADB 2022.1.22](https://github.com/dengzii/WiFiADB/releases/tag/v2022.1.22)
**Describe the bug**
mark not save when insert mark

**To Reproduce**
insert mark
close window
open WiFi ADB
mark is empty
**Screenshots**

**Context Log**
From `Menu > Main > Log`
07-24/11:54 Config.saveDevice:57: [Device(sn='192.168.1.126:5555', ip='192.168.1.126', model='MiTV_AESP0', modelName='aquaman', port='5555', status=CONNECTED, broadcastAddress='',mark=test-mark1)]
07-24/11:54 Config.loadDevices:50: [Device(sn='192.168.1.126:5555', ip='192.168.1.126', model='MiTV_AESP0', modelName='aquaman', port='5555', status=DISCONNECTED, broadcastAddress='',mark=test-mark1)]
07-24/11:54 CmdUtils.execSync:48: adb devices -l
07-24/11:54 CmdUtils.resolve$lambda-2:76: >List of devices attached
07-24/11:54 CmdUtils.resolve$lambda-2:76: >WCR7N18525006454       device product:CLT-L29 model:CLT_L29 device:HWCLT transport_id:5
07-24/11:54 CmdUtils.resolve$lambda-2:76: >192.168.1.113:5557     device product:CLT-L29 model:CLT_L29 device:HWCLT transport_id:3
07-24/11:54 CmdUtils.resolve$lambda-2:76: >192.168.1.126:5555     device product:aquaman model:MiTV_AESP0 device:aquaman transport_id:2
07-24/11:54 CmdUtils.resolve$lambda-2:76: >
07-24/11:54 CmdUtils.execSync:48: adb -s WCR7N18525006454 shell  ip addr show wlan0
07-24/11:54 CmdUtils.resolve$lambda-2:76: >31: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
07-24/11:54 CmdUtils.resolve$lambda-2:76: >    link/ether b8:94:36:2a:e5:0b brd ff:ff:ff:ff:ff:ff
07-24/11:54 CmdUtils.resolve$lambda-2:76: >    inet 192.168.1.113/24 brd 192.168.1.255 scope global wlan0
07-24/11:54 CmdUtils.resolve$lambda-2:76: >       valid_lft forever preferred_lft forever
07-24/11:54 CmdUtils.resolve$lambda-2:76: >    inet6 2405:9800:bc10:b4d1:1180:3d7e:2479:f856/64 scope global temporary dynamic 
07-24/11:54 CmdUtils.resolve$lambda-2:76: >       valid_lft 600232sec preferred_lft 81808sec
07-24/11:54 CmdUtils.resolve$lambda-2:76: >    inet6 2405:9800:bc10:b4d1:ba94:36ff:fe2a:e50b/64 scope global dynamic mngtmpaddr 
07-24/11:54 CmdUtils.resolve$lambda-2:76: >       valid_lft 2591317sec preferred_lft 2591317sec
07-24/11:54 CmdUtils.resolve$lambda-2:76: >    inet6 fe80::ba94:36ff:fe2a:e50b/64 scope link 
07-24/11:54 CmdUtils.resolve$lambda-2:76: >       valid_lft forever preferred_lft forever
07-24/11:54 Config.saveDevice:57: [Device(sn='192.168.1.113:5557', ip='192.168.1.113', model='CLT_L29', modelName='CLT-L29', port='5557', status=CONNECTED, broadcastAddress='',mark=), Device(sn='192.168.1.126:5555', ip='192.168.1.126', model='MiTV_AESP0', modelName='aquaman', port='5555', status=CONNECTED, broadcastAddress='',mark=)]
07-24/11:55 Config.saveDevice:57: [Device(sn='192.168.1.113:5557', ip='192.168.1.113', model='CLT_L29', modelName='CLT-L29', port='5557', status=CONNECTED, broadcastAddress='',mark=test-mark2), Device(sn='192.168.1.126:5555', ip='192.168.1.126', model='MiTV_AESP0', modelName='aquaman', port='5555', status=CONNECTED, broadcastAddress='',mark=test-mark3)]
07-24/11:55 CmdUtils.execSync:48: adb version
07-24/11:55 CmdUtils.resolve$lambda-2:76: >Android Debug Bridge version 1.0.41
07-24/11:55 CmdUtils.resolve$lambda-2:76: >Version 33.0.2-8557947
07-24/11:55 CmdUtils.resolve$lambda-2:76: >Installed as C:\Users\punpro\AppData\Local\Android\Sdk\platform-tools\adb.exe
07-24/11:55 Config.loadDevices:50: [Device(sn='192.168.1.113:5557', ip='192.168.1.113', model='CLT_L29', modelName='CLT-L29', port='5557', status=DISCONNECTED, broadcastAddress='',mark=test-mark2), Device(sn='192.168.1.126:5555', ip='192.168.1.126', model='MiTV_AESP0', modelName='aquaman', port='5555', status=DISCONNECTED, broadcastAddress='',mark=test-mark3)]
07-24/11:55 CmdUtils.execSync:48: adb devices -l
07-24/11:55 CmdUtils.resolve$lambda-2:76: >List of devices attached
07-24/11:55 CmdUtils.resolve$lambda-2:76: >WCR7N18525006454       device product:CLT-L29 model:CLT_L29 device:HWCLT transport_id:5
07-24/11:55 CmdUtils.resolve$lambda-2:76: >192.168.1.113:5557     device product:CLT-L29 model:CLT_L29 device:HWCLT transport_id:3
07-24/11:55 CmdUtils.resolve$lambda-2:76: >192.168.1.126:5555     device product:aquaman model:MiTV_AESP0 device:aquaman transport_id:2
07-24/11:55 CmdUtils.resolve$lambda-2:76: >
07-24/11:55 CmdUtils.execSync:48: adb -s WCR7N18525006454 shell  ip addr show wlan0
07-24/11:55 CmdUtils.resolve$lambda-2:76: >31: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
07-24/11:55 CmdUtils.resolve$lambda-2:76: >    link/ether b8:94:36:2a:e5:0b brd ff:ff:ff:ff:ff:ff
07-24/11:55 CmdUtils.resolve$lambda-2:76: >    inet 192.168.1.113/24 brd 192.168.1.255 scope global wlan0
07-24/11:55 CmdUtils.resolve$lambda-2:76: >       valid_lft forever preferred_lft forever
07-24/11:55 CmdUtils.resolve$lambda-2:76: >    inet6 2405:9800:bc10:b4d1:1180:3d7e:2479:f856/64 scope global temporary dynamic 
07-24/11:55 CmdUtils.resolve$lambda-2:76: >       valid_lft 600133sec preferred_lft 81709sec
07-24/11:55 CmdUtils.resolve$lambda-2:76: >    inet6 2405:9800:bc10:b4d1:ba94:36ff:fe2a:e50b/64 scope global dynamic mngtmpaddr 
07-24/11:55 CmdUtils.resolve$lambda-2:76: >       valid_lft 2591218sec preferred_lft 2591218sec
07-24/11:55 CmdUtils.resolve$lambda-2:76: >    inet6 fe80::ba94:36ff:fe2a:e50b/64 scope link 
07-24/11:55 CmdUtils.resolve$lambda-2:76: >       valid_lft forever preferred_lft forever
07-24/11:55 Config.saveDevice:57: [Device(sn='192.168.1.113:5557', ip='192.168.1.113', model='CLT_L29', modelName='CLT-L29', port='5557', status=CONNECTED, broadcastAddress='',mark=), Device(sn='192.168.1.126:5555', ip='192.168.1.126', model='MiTV_AESP0', modelName='aquaman', port='5555', status=CONNECTED, broadcastAddress='',mark=)]

**Comment by dengzii** [comment]
If you close the window while editing `Mark`, it will not save, `Mark` will not be saved, please unfocus after editing.
