### ISSUE TITLE
能否实现局域网IP扫描?

### ISSUE THREAD

**Issue by zuilintan** [dengzii/WiFiADB#6]
RT, 不过感觉应该不太好实现

**Comment by dengzii** [comment]
这个我刚开始想过， 都有测试代码，实现好像是不麻烦的，主要是没想到这个功能的价值在哪

**Comment by zuilintan** [comment]
比如偶尔没数据线也没办法知道ip(原生Setting被隐藏)的情况

**Comment by badboy-tian** [comment]
这个功能好~ 如何能实现那就太好了

**Comment by dengzii** [comment]
> 这个功能好~ 如何能实现那就太好了

关键是手机在不使用的情况下不一定什么时候会关闭 adb(5555+) 端口.
除非手动在手机上打开这个端口

**Comment by badboy-tian** [comment]
只需要第一次usb链接  后面只要手机没关机 这个5555是一直开着的吧?  有时候出门办事儿 回来ip地址变了 又得用usb链接adb wifi  确实挺麻烦的  而且手机一般很少关机 除非没电了自动关机

**Comment by dengzii** [comment]
> 只需要第一次usb链接 后面只要手机没关机 这个5555是一直开着的吧? 有时候出门办事儿 回来ip地址变了 又得用usb链接adb wifi 确实挺麻烦的 而且手机一般很少关机 除非没电了自动关机

有些手机重启才关, 有些可能没使用一段时间就关, 有些则断开就关 

那我后面考虑加上这个功能

**Comment by badboy-tian** [comment]
嗯 谢谢~ 有空再说吧 工作要紧

dengzi <notifications@github.com> 于2020年8月28日周五 上午10:38写道：

**Comment by zuilintan** [comment]
> > 这个功能好~ 如何能实现那就太好了
> 
> 关键是手机在不使用的情况下不一定什么时候会关闭 adb(5555+) 端口.
> 除非手动在手机上打开这个端口

我这边一般是在获取root权限后, 
echo /system/build.prop service.adb.tcp.port=5555

**Comment by zuilintan** [comment]
对我们做车机系统的而言, 有这个功能的确会方便不少

**Comment by dengzii** [comment]
> > > 这个功能好~ 如何能实现那就太好了
> > 
> > 
> > 关键是手机在不使用的情况下不一定什么时候会关闭 adb(5555+) 端口.
> > 除非手动在手机上打开这个端口
> 
> 我这边一般是在获取root权限后,
> echo /system/build.prop service.adb.tcp.port=5555

那我下次更新试试加上这个

**Comment by dengzii** [comment]
久等了, 扫描 beta 终于好了 😂
