### ISSUE TITLE
Device is auto connected every minute

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [dengzii/WiFiADB#8]
I have a device connected once and press disconnect. It connects again automatically after a minute or so.
how to stop this?
<img width="319" alt="Screen Shot 1399-03-10 at 6 37 23 PM" src="https://user-images.githubusercontent.com/5219339/83330552-e8a9cd80-a2a4-11ea-949c-063030095843.png">
<img width="995" alt="Screen Shot 1399-03-10 at 6 37 46 PM" src="https://user-images.githubusercontent.com/5219339/83330554-e9dafa80-a2a4-11ea-95b6-42545709db08.png">

**Comment by dengzii** [comment]
This is not a plugin feature, can you privide the plugin log, the log is in Main > Log
